# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Антон Ненашев
title: Python-developer
email: anton.nenashev2015@yandex.ru

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  foxonn
stackoverflow_username: "8963691"
telegram_username: "@psihonort"
codewars_username: "Foxonn"

# Additional icon links
additional_links:
- title: telegram
  icon: fa-telegram
  url: https://t.me/psihonort

# - title: another link
#   icon: font awesome brand icon name (eg. fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-MZJ9XTX"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: Обо мне
about_profile_image: images/self.jpg
about_content: | # this will include new lines to allow paragraphs
  Разрабатывал API сервисы. Проектировал структуру базы данных. Работал в командах от 2-14 человек.
  Придерживаюсь стандартов разработки языка. Следую SOLID припципам, пишу тесты и типизирую свой код.
  
  
  Мой стек:

  <mark>Python</mark> <mark>GIT</mark> <mark>PostgreSQL</mark> <mark>Docker</mark> <mark>Redis</mark>
  <mark>RabbitMQ</mark> <mark>AsyncIO</mark> <mark>FastAPI</mark> <mark>Pydantic</mark> <mark>Pytest</mark>
  <mark>Unix</mark>

# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# More Section
# more_title: Немного обо мне #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  До того как перешёл на Python, занимался разработкой и поддержкой сайтов на PHP. Знаком с разработкой 
  не только со стороны backend`а. 
  Причиной смены языка послужило большая универсальность языка. Было интересно писать
  не только сетевые приложения + синтаксис языка пришёлся по вкусу.

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
